name: Compile Sketches

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Initialize Arduino CLI configuration
      run: arduino-cli config init

    - name: Add STM32 board manager URL
      run: arduino-cli config add board_manager.additional_urls https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json

    - name: Update core index
      run: arduino-cli core update-index

    - name: Install STM32 platform
      run: arduino-cli core install STMicroelectronics:stm32

    - name: Install RP2040 platform
      run: arduino-cli core install arduino:mbed_rp2040

    - name: Compile stm32f446re_master
      run: arduino-cli compile --fqbn STMicroelectronics:stm32:Nucleo_64:pnum=NUCLEO_F446RE arduino_spi_dma_crc/stm32f446re_master/stm32f446re_master.ino

    - name: Compile xiao_rp2040_slave
      run: arduino-cli compile --fqbn arduino:mbed_rp2040:seeed_xiao_rp2040 arduino_spi_dma_crc/xiao_rp2040_slave/xiao_rp2040_slave.ino

    - name: Compile stm32f446re_loopback
      run: arduino-cli compile --fqbn STMicroelectronics:stm32:Nucleo_64:pnum=NUCLEO_F446RE stm32f446re_loopback/stm32f446re_loopback.ino

    - name: Compile xiao_rp2040_loopback
      run: arduino-cli compile --fqbn arduino:mbed_rp2040:seeed_xiao_rp2040 xiao_rp2040_loopback/xiao_rp2040_loopback.ino
