name: Compile Sketches

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Initialize Arduino CLI configuration
        run: arduino-cli config init

      - name: Add STM32 and RP2040 board manager URLs
        run: |
          arduino-cli config add board_manager.additional_urls https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json
          arduino-cli config add board_manager.additional_urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json

      - name: Update core index
        run: arduino-cli core update-index

      - name: Install STM32 and RP2040 platforms
        run: |
          arduino-cli core install STMicroelectronics:stm32
          arduino-cli core install rp2040:rp2040

      - name: Compile STM32 projects
        run: |
          arduino-cli compile --fqbn STMicroelectronics:stm32:Nucleo_64:pnum=NUCLEO_F446RE arduino_spi_dma_crc/stm32f446re_master
          arduino-cli compile --fqbn STMicroelectronics:stm32:Nucleo_64:pnum=NUCLEO_F446RE stm32f446re_loopback

      - name: Compile RP2040 projects
        run: |
          arduino-cli compile --fqbn rp2040:rp2040:seeed_xiao_rp2040 arduino_spi_dma_crc/xiao_rp2040_slave
          arduino-cli compile --fqbn rp2040:rp2040:seeed_xiao_rp2040 xiao_rp2040_loopback
